config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  resources :topics, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  resources :events, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  resources :abouts, only: [:index]
  resources :contacts, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :e_image, ImageUploader
  belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :topics
  has_many :events
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: :new

  def index
    @events = Event.order("created_at DESC")
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy if event.user_id == current_user.id
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    if event.user_id == current_user.id
      event.update(event_params)
    end
  end

  def event_params
    params.require(:event).permit(:e_title, :time, :date, :e_body, :e_image, :host, :place, :price).merge(user_id: current_user.id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @topics = Topic.order("created_at DESC").limit(3)
    @events = Event.order("created_at DESC").limit(3)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, only: :new

  def index
    @topics = Topic.order("created_at DESC")
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to @topic
    else
      render :new
    end
  end

  def destroy
    topic = Topic.find(params[:id])
    topic.destroy if topic.user_id == current_user.id
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    topic = Topic.find(params[:id])
    if topic.user_id == current_user.id
      topic.update(topic_params)
    end
  end

  def topic_params
    params.require(:topic).permit(:title, :body, :image).merge(user_id: current_user.id)
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/abouts/index.html.erb
  <div class="about-container">
    <div class="main">
    </div>

    <section class="about">
      <h2>「よかもんジャーナル」とは</h2>
      <div class="about-contents">
        <h3>福岡の良いものを<br>誰でも簡単に投稿できるサービス</h3>
        <p>福岡のイベントやニュースを誰もが観覧でき、ユーザー登録すれば投稿もできるサービスを作りました。<br>福岡は料理が美味しい！可愛い子が多い！空港から市街地までが近くて便利！などなど、様々な声を聞きます。そんな福岡の「よかもん（良いもの）」を集めて発信してみませんか？</p>
      </div>
    </section>

    <section class="feature">
      <h2>「よかもんジャーナル」の使用方法</h2>
      <p>ニュースやイベントの観覧は誰でもできます。<br>
      自ら情報を発信したい方はまずは右上の「新規登録」ボタンからユーザー登録を行ってください。登録ができれば「POST NEWS」または「POST EVENT」を押せば簡単に投稿ができます。<br>
    もしも自分の投稿を「編集」・「削除」したい場合は、投稿した記事のページで ▼ ボタンにカーソルを合わせると「編集」「削除」のボタンが出てきますので、そちらから行えます。<br>
  さっそく使ってみてください！</p>
    </section>

    <section class="outline">
      <h2>制作概要</h2>
      <p>
        プログラミングスクールでRuby on Railsを学び、制作物としてこのよかもんジャーナルをつくりました。このwebアプリはrailsで「ユーザー登録機能」「投稿機能」「投稿者のみが削除できる機能」「投稿者のみが編集できる機能」などを実装しています。利用者が簡単に使えるようにユーザー登録しなくてもイベントのタイトルや詳細が確認できるなど、こだわりがたくさんあります。
        是非利用して、機能を確認してみてください。
      </p>
    </section>

    <div class="btn" id="about-b">
      <div class="btn-content">
        <div class="btn-hover"></div>
        <%= link_to 'top', root_path, class: "btn--readmore" %>
      </div>
    </div>
  </div>

app/views/contacts/index.html.erb
<div class="form-container">
  <h3>お問い合わせ</h3>

  <div class="form-content">
    <p id="red-border">当サイトにお越しいただき、ありがとうございます。<br>ご質問やお問い合わせなど、下記フォームよりお願いいたします。<br>（<span>※</span>は必須入力項目となります。）</p>

    <div class="form">
      <form>
        <table>
          <tbody>
            <tr>
              <th>
                氏名<span>*</span>
              </th>
              <td>
                <input type="text" name="name" placeholder="山田 太郎">
              </td>
            </tr>
            <tr>
              <th>
                ふりがな
              </th>
              <td>
                <input type="text" name="name-furi" placeholder="やまだ たろう">
              </td>
            </tr>
            <tr>
              <th>
                郵便番号
              </th>
              <td>
                <input type="text" name="zip-cord" placeholder="123-4567">
              </td>
            </tr>
            <tr>
              <th>
                メールアドレス<span>*</span>
              </th>
              <td>
                <input type="text" name="email" placeholder="info@yokamonjouornal.com">
              </td>
            </tr>
            <tr>
              <th>
                お問い合わせ内容<span>*</span>
              </th>
              <td>
                <textarea name="message" placeholder="こちらにお問い合わせ内容を記入してください。"></textarea>
              </td>
            </tr>
          </tbody>
        </table>
        <p>入力内容を再度ご確認の上、間違えがなければ下の送信ボタンをクリック・タップしてください。</p>
        <p class="submit">
          <input type="submit" value="上記の内容で送信する" class="submit-btn">
        </p>
      </form>
    </div>

    <div class="notes">
      <h4>注意事項</h4>
      <p>恐れ入ります。現在こちらのお問い合わせフォームは使用できなくなっております。
      内容を送信しても制作者の元に届かないようになっておりますので、ご了承ください。</p>
    </div>
  </div>
</div>

app/views/events/destroy.html.erb
<div class="news-contents">
  <div class="n-title">
    <h3 class="destroy">イベントの投稿を削除しました。</h3>
  </div>
</div>
<div class="n-buttons-destroy">
  <div class="n-buttons-contents">
    <ul>
      </li>
      <li>
        <div class="btn">
          <div class="btn-content">
            <div class="btn-hover"></div>
            <%= link_to "event top", events_path, class: 'btn--readmore' %>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/events/edit.html.erb
<div class="form-container">
  <h3>イベント編集</h3>

  <div class="form-content">

    <div class="form">
      <%= form_for @event do |f| %>
        <table>
          <tbody>
            <tr>
              <th>
                <%= f.label :イベントタイトル %><span>*</span>
              </th>
              <td>
                <%= f.text_field :e_title, placeholder: 'イベント名を記入してください。' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :時間 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :time, placeholder: '5/4 10:30-12:30' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :開催日 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :date, placeholder: '05月04日' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :主催者 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :host, placeholder: '主催者を記入してください。' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :場所 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :place, placeholder: 'イベント開催場所を記入してください。' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :参加費 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :price, placeholder: '無料' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :イベントの内容 %><span>*</span>
              </th>
              <td>
                <%= f.text_area :e_body, placeholder: 'イベントの内容を記入してください。' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :画像ファイル添付 %>
              </th>
              <td>
                <%= f.file_field :e_image %>
              </td>
            </tr>
          </tbody>
        </table>
        <p>入力内容を再度ご確認の上、間違えがなければ下の送信ボタンをクリック・タップしてください。</p>
        <p class="submit">
          <%= f.submit 'イベントを編集する', class: 'submit-btn' %>
        </p>
      <% end %>
    </div>
    </div>

    <div class="notes">
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="container-title">
    <h3>イベント</h3>
  </div>
  <div class="event-index">
    <div class="event-index-box">
      <ul>
        <% @events.each do |event| %>
        <li class="event-info">
          <%= link_to event_path(event.id), class: 'event-info' do %>
            <div class="before">read more</div>
            <div class="event-date"><%= event.created_at.strftime("%Y.%m.%d") %></div>
            <div class="event-img">
              <% unless event.e_image.blank? %>
                <%= image_tag event.e_image.url %>
              <% else %>
                <div class="no-image">
                  <p>NO IMAGE</p>
                </div>
              <% end %>
            </div>
            <div class="event-details">
              <div class="event-name">
                <p>イベント名：<%= event.e_title %></p>
              </div>
              <div class="event-host">
                <p>主催：<%= event.host %></p>
              </div>
              <div class="event-price">
                <p>参加費：<%= event.price %></p>
              </div>
            </div>
           <% end %>
         </li>
       <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="form-container">
  <h3>イベント投稿</h3>

  <div class="form-content">
    <p id="red-border">イベントの投稿は下記フォームよりお願いいたします。<br>（<span>※</span>は必須入力項目となります。）</p>

    <div class="form">
      <%= form_for @event do |f| %>
        <table>
          <tbody>
            <tr>
              <th>
                <%= f.label :イベントタイトル %><span>*</span>
              </th>
              <td>
                <%= f.text_field :e_title, placeholder: 'イベント名を記入してください。' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :時間 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :time, placeholder: '5/4 10:30-12:30' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :開催日 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :date, placeholder: '05月04日' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :主催者 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :host, placeholder: '主催者を記入してください。' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :場所 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :place, placeholder: 'イベント開催場所を記入してください。' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :参加費 %><span>*</span>
              </th>
              <td>
                <%= f.text_field :price, placeholder: '無料' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :イベントの内容 %><span>*</span>
              </th>
              <td>
                <%= f.text_area :e_body, placeholder: 'イベントの内容を記入してください。' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :画像ファイル添付 %>
              </th>
              <td>
                <%= f.file_field :e_image %>
              </td>
            </tr>
          </tbody>
        </table>
        <p>入力内容を再度ご確認の上、間違えがなければ下の送信ボタンをクリック・タップしてください。</p>
        <p class="submit">
          <%= f.submit 'イベントを投稿する', class: 'submit-btn' %>
        </p>
      <% end %>
    </div>
    </div>

    <div class="notes">
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="event-container">
  <div class="event-details">
    <dl class="event-name">
      <dt>イベント名：</dt>
      <dd><%= @event.e_title %></dd>
    </dl>
    <dl class="event-date">
      <dt>開催日：</dt>
      <dd><%= @event.date %></dd>
    </dl>
    <dl class="event-time">
      <dt>時間：</dt>
      <dd><%= @event.time %></dd>
    </dl>
  </div>

  <div class="event-poster">
  <p class="post-user">投稿者： <%= @event.user.nickname %>さん</p>
    <% unless @event.e_image.blank? %>
      <%= image_tag @event.e_image.url %>
    <% else %>
      <div class="no-image-event">
        <p>No Image</p>
      </div>
    <% end %>
  </div>

  <div class="event-text">
    <p><%= @event.e_body %></p>
    <% if user_signed_in? && current_user.id == @event.user_id %>
      <div class="more">
        <span><i class="fa fa-chevron-circle-down fa-lg"></i></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', "/events/#{@event.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to '削除', "/events/#{@event.id}", method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="event-details" id="bottom-detail">
    <dl class="event-host">
      <dd>主催：</dd>
      <dd><%= @event.host %></dd>
    </dl>
    <dl class="event-place">
      <dd>場所：</dd>
      <dd><%= @event.place %></dd>
    </dl>
    <dl class="event-price">
      <dd>参加費：</dd>
      <dd><%= @event.price %></dd>
    </dl>
  </div>

  <div class="e-button">
    <ul>
      <li class="first-b">
        <div class="btn">
          <div class="btn-content">
            <div class="btn-hover"></div>
            <a class="btn--readmore" href="#">prev</a>
          </div>
        </div>
      </li>
      <li>
        <div class="btn">
          <div class="btn-content">
            <div class="btn-hover"></div>
            <%= link_to "event top", events_path, class: 'btn--readmore' %>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/events/update.html.erb
<div class="news-contents">
  <div class="n-title">
    <h3 class="destroy">イベントの投稿を更新しました。</h3>
  </div>
</div>
<div class="n-buttons-destroy">
  <div class="n-buttons-contents">
    <ul>
      </li>
      <li>
        <div class="btn">
          <div class="btn-content">
            <div class="btn-hover"></div>
            <%= link_to "event top", events_path, class: 'btn--readmore' %>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer--wrapper">
    <div class="footer-left">
      <a class="footer-logo" href="#">
        <%= image_tag 'foot-logo.png' %>
      </a>
      <div class="dougo-info">
        <div class="address">
          <p>福岡の良いものを全国に届けよう<br>自ら投稿し、発信できる<br>福岡の情報サイト<br>まずはユーザー登録から！<br>お気軽にどうぞ</p>
        </div>
        <div class="tel">
          福岡 よかもんジャーナル<br><br><br>
        </div>
      </div>
    </div>
    <div class="footer-right">
      <div class="footer--nav">
        <ul>
          <li>
            <%= link_to "よかもんジャーナルとは", abouts_path %>
          </li>
          <li>
            <%= link_to "最新情報", topics_path %>
          </li>
          <li>
            <%= link_to "イベント情報", events_path %>
          </li>
          <li>
            <%= link_to "ニュース投稿", new_topic_path %>
          </li>
          <li>
            <%= link_to "イベント投稿", new_event_path %>
          </li>
          <li>
            <%= link_to "お問い合わせ", contacts_path %>
          </li>
        </ul>
      </div>
    </div>
    <p class="copyright">
      Copyright yokamon-journal, 2019 All Rights Reserved.
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="header--contents">
    <div class="logo">
      <%= link_to root_path do %>
        <%=image_tag('yokamon-logo.png')%>
      <% end %>
    </div>
    <ul class="header--topnav">
      <% if user_signed_in? %>
        <li class="header--topnav__lung user">
          <span><%= current_user.nickname %></span>
        </li>
        <li class="header--topnav__lung signIn">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="header--topnav__lung en">
          <%= link_to "ログイン", new_user_session_path, class: 'post' %>
        </li>
        <li class="header--topnav__lung signIn">
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </li>
      <% end %>
    </ul>

    <div class="header--glovalnav">
      <ul>
        <li>
          <%= link_to abouts_path, method: :get do %>
            <span class="eng">ABOUT</span>
            <span class="ja">よかもんジャーナルとは</span>
          <% end %>
        </li>
        <li>
          <%= link_to topics_path, method: :get do %>
            <span class="eng">NEWS</span>
            <span class="ja">最新情報</span>
          <% end %>
        </li>
        <li>
          <%= link_to events_path, method: :get do %>
            <span class="eng">EVENT</span>
            <span class="ja">イベント情報</span>
          <% end %>
        </li>
        <li>
          <%= link_to new_topic_path, method: :get do %>
            <span class="eng">POST NEWS</span>
            <span class="ja">ニュース投稿</span>
          <% end %>
        </li>
        <li>
          <%= link_to new_event_path, method: :get do %>
            <span class="eng">POST EVENTS</span>
            <span class="ja">イベント投稿</span>
          <% end %>
        </li>
        <li class="last">
          <%= link_to contacts_path, method: :get do %>
            <span class="eng">CONTACT</span>
            <span class="ja">お問い合わせ</span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>よかもんジャーナル</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/top/index.html.erb
<div class="main">
  <div class="autoplay">
    <%= image_tag 'maizuru-park.jpg', class: 'main--img' %>
    <%= image_tag 'tenjin.jpg', class: 'main--img' %>
    <%= image_tag 'tenjin-station.jpg', class: 'main--img' %>
  </div>
</div>
<div class="container">
  <section class="news">
    <h2>
      NEWS
    </h2>
    <ul class="news--contents">
      <% @topics.each do |topic| %>
        <li>
          <%= link_to topic_path(topic.id), class: "news--contents--a" do %>
            <span class="news-date"><%= topic.created_at.strftime("%Y.%m.%d") %></span>
            <span><%= topic.title %></span>
            <i class="fa fa-caret-right"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="btn">
      <div class="btn-content">
        <div class="btn-hover"></div>
        <%= link_to "read more", topics_path, class: "btn--readmore" %>
      </div>
    </div>
  </section>

  <section class="event">
    <h2>
      EVENT
    </h2>
    <ul>
      <% @events.each do |event| %>
        <li>
          <%= link_to event_path(event.id), class: "event--box" do %>
            <div class="before">read more</div>
            <div class="event-image">
              <% unless event.e_image.blank? %>
                <%= image_tag event.e_image.url %>
              <% else %>
                <div class="no-image">
                  <p>NO IMAGE</p>
                </div>
              <% end %>
            </div>
            <div class="event-date">
              <p class="round-date"><%= event.created_at.strftime("%Y") %><br><%= event.created_at.strftime("%m.%d") %></p>
            </div>
            <div class="contents">
              <p class="contents--title"><%= event.e_title %></p>
              <p><%= event.host %><br><%= event.place %></p>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="btn">
      <div class="btn-content">
        <div class="btn-hover"></div>
        <%= link_to "read more", events_path, class: "btn--readmore" %>
      </div>
    </div>
  </section>
</div>

app/views/topics/destroy.html.erb
<div class="news-contents">
  <div class="n-title">
    <h3 class="destroy">ニュースの投稿を削除しました。</h3>
  </div>
</div>
<div class="n-buttons-destroy">
  <div class="n-buttons-contents">
    <ul>
      </li>
      <li>
        <div class="btn">
          <div class="btn-content">
            <div class="btn-hover"></div>
            <%= link_to "news top", topics_path, class: 'btn--readmore' %>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="form-container">
  <h3>編集する</h3>

  <div class="form-content">

    <div class="form">
      <%= form_for @topic do |f| %>
        <table>
          <tbody>
            <tr>
              <th>
                <%= f.label :ニュースタイトル %><span>*</span>
              </th>
              <td>
                <%= f.text_field :title, placeholder: 'ワークショップ開催のお知らせ' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :ニュース内容 %><span>*</span>
              </th>
              <td>
                <%= f.text_area :body, placeholder: 'お知らせの内容を記入してください。' %>
              </td>
            </tr>
            <tr>
              <th>
                <%= f.label :画像ファイル添付 %>
              </th>
              <td>
                <%= f.file_field :image %>
              </td>
            </tr>
          </tbody>
        </table>
        <p>入力内容を再度ご確認の上、間違えがなければ下の送信ボタンをクリック・タップしてください。</p>
        <p class="submit">
          <%= f.submit 'ニュースを編集する', class: 'submit-btn' %>
        </p>
      <% end %>
    </div>
    </div>

    <div class="notes">
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="container-title">
    <h3>最新情報</h3>
  </div>

  <section class="news-sec">
    <h2 class="news-month">2019 02 February</h2>
    <ul>
      <% @topics.each do |topic| %>
        <li>
          <%= link_to topic_path(topic.id), class: 'news-box' do %>
            <div class="before">read more</div>
            <div class="news-date"><%= topic.created_at.strftime("%Y.%m.%d") %></div>
            <div class="news-image">
              <% unless topic.image.blank? %>
                <%= image_tag topic.image.url %>
              <% else %>
                <div class="no-image">
                  <p>NO IMAGE</p>
                </div>
              <% end %>
              <div class="red-box">
                <p><%= topic.title %><i class="fa fa-caret-right"></i></p>
              </div>
            </div>
           <% end %>
        </li>
      <% end %>
    </ul>

  <section class="news-sec">
    <h2 class="news-month">2019 01 January</h2>
    <ul>
      <li>
        <a class="news-box" href="#">
          <div class="before">read more</div>
          <div class="news-date">2019.01.30</div>
          <div class="news-image">
            <%= image_tag 'art1.jpg' %>
            <div class="red-box">
              <p>お知らせテストのお知らせ<i class="fa fa-caret-right"></i></p>
            </div>
          </div>
         </a>
      </li>
      <li>
        <a class="news-box" href="#">
          <div class="before">read more</div>
          <div class="news-date">2019.01.30</div>
          <div class="news-image">
            <%= image_tag 'art1.jpg' %>
            <div class="red-box">
              <p>お知らせテストのお知らせ<i class="fa fa-caret-right"></i></p>
            </div>
          </div>
         </a>
      </li>
    </ul>
  </section>
</div>

app/views/topics/show.html.erb
<div class="news-contents">
  <div class="n-title">
    <h2><%= @topic.title %></h2>
    <div class="news-date"><%= @topic.created_at.strftime("%Y.%m.%d") %></div>
    <div class="nickname">
      <p>投稿者： <%= @topic.user.nickname %>さん</p>
    </div>
  <div class="news-contents-pic">
    <% unless @topic.image.blank? %>
      <%= image_tag @topic.image.url %>
    <% end %>
  </div>
</div>
</div>
<div class="news-text">
  <p><%= @topic.body %></p>
  <% if user_signed_in? && current_user.id == @topic.user_id %>
    <div class="more">
      <span><i class="fa fa-chevron-circle-down fa-lg"></i></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/topics/#{@topic.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/topics/#{@topic.id}", method: :delete %>
        </li>
      </ul>
    </div>
  <% end %>
</div>
<div class="n-buttons">
  <div class="n-buttons-contents">
    <ul>
      <li class="first-button">
        <div class="btn">
          <div class="btn-content">
            <div class="btn-hover"></div>
            <a class="btn--readmore" href="#">prev</a>
          </div>
        </div>
      </li>
      <li>
        <div class="btn">
          <div class="btn-content">
            <div class="btn-hover"></div>
            <%= link_to "news top", topics_path, class: 'btn--readmore' %>
          </div>
        </div>
      </li>
      <li class="last-button">
        <div class="btn">
          <div class="btn-content">
            <div class="btn-hover"></div>
            <a class="btn--readmore" href="#">next</a>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/topics/update.html.erb
<div class="news-contents">
  <div class="n-title">
    <h3 class="destroy">ニュースの投稿を更新しました。</h3>
  </div>
</div>
<div class="n-buttons-destroy">
  <div class="n-buttons-contents">
    <ul>
      </li>
      <li>
        <div class="btn">
          <div class="btn-content">
            <div class="btn-hover"></div>
            <%= link_to "news top", topics_path, class: 'btn--readmore' %>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>